Name:           ros-melodic-rexrov2-control
Version:        0.1.3
Release:        0%{?dist}
Summary:        ROS rexrov2_control package

Group:          Development/Libraries
License:        Apache-2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-gazebo-ros
Requires:       ros-melodic-gazebo-ros-control
Requires:       ros-melodic-uuv-control-cascaded-pid
Requires:       ros-melodic-uuv-thruster-manager
Requires:       ros-melodic-uuv-trajectory-control
BuildRequires:  ros-melodic-catkin

%description
The rexrov2_control package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Sat Apr 06 2019 Musa Morena Marcusso Manhaes <Musa.Marcusso@de.bosch.com> - 0.1.3-0
- Autogenerated by Bloom

